### ISSUE TITLE
Remove unnecessary backslashes

### ISSUE THREAD

**Issue by corvannoorloos** [Cerdic/CSSTidy#21]
First of all, it's great to see this project is still alive. I'm really enjoying the changes made after v1.3 :)

There's however a (new) minor issue with the "Remove unnecessary backslashes" checkbox.

Using this with a "custom layout", this feature simply doesn't work anymore. Also after submitting the "Process CSS" button it will automatically uncheck itself again.

**Comment by Cerdic** [comment]
Not sure if it's still an issue (ok I know I was long to answer :) )
The option remove_bslash is checked by default, and reading into the code it seems it's only used to remove backslask on unicode notation.

However there is no test case in the unit test about this option, so not wanting to change anything without any sample of what this should change in the CSS.

Please feel free to reopen this issue with providing some test case and expected output so I can complete the unit tests and fix this issue if necessary
