### ISSUE TITLE
$version still showing v1.5.2

### ISSUE THREAD

**Issue by amiga-500** [Cerdic/CSSTidy#43]
This is not an issue but noticed the **_$version_** member variable is still set to "_1.5.2_" instead of "_**1.5.5**_" (current version)

File: _**class.csstidy.php**_
Line #: **_150_**

Currently:
```php
public $version = '1.5.2';
```

Should be:
```php
public $version = '1.5.5';
```

**Comment by Cerdic** [comment]
ok, this is now fixed, thanks!
