### ISSUE TITLE
Keyframes doesn't work

### ISSUE THREAD

**Issue by PeterTillema** [Cerdic/CSSTidy#48]
Hi,

I'm not sure whether this is the right place to report bugs, so feel free to point me elsewhere if needed. I have a very simple CSS file:
```
@keyframes blink {
  0% { background: #7e7; }
  50% { background: none; }
  100% { background: #7e7; }
}
```

When throwing this file at CSSTidy, it gives me this result:
```
-----------------------------------

50% {
background:none;
}

100% {
background:#7e7;
}
-----------------------------------

1: Invalid @-rule: keyframes (removed)
2: Invalid property in CSS2.1: 0background

-----------------------------------
```
which is obviously not right, because `@keyframes blink` is valid syntax, right?

**Comment by Cerdic** [comment]
I added a unit test for this case just to check and it's OK
I think the trouble was CSS3.0 wasn't in the CSS Level select in the optimiser interface, that's fixed with 28fe1d6
