### ISSUE TITLE
Any way to optimize Firefox CSS files?

### ISSUE THREAD

**Issue by necros2k7** [Cerdic/CSSTidy#50]
subj

**Comment by Cerdic** [comment]
Not sure to understand the question. The CSS Optimiser can optimise any CSS file, what are you calling "Firefox CSS files"?

**Comment by necros2k7** [comment]
I mean CSSes which are located in chrome/toolkit/content/global/ and other dirs of omni.ja Firefox file.
Optimization breaks normal browser operation.  Can you try to reproduce it?

**Comment by Cerdic** [comment]
Please give a practical example of a broken CSS. Try to find which one is broken and where it is. Feel free to reopen the issue with more details
