### ISSUE TITLE
Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by seezee** [Cerdic/CSSTidy#56]
CSS Tidy generates these errors when running setting WP_DEBUG: TRUE.

`csstidy has a deprecated constructor in /app/public/wp-content/plugins/wp-foft-loader/includes/csstidy/class.csstidy.php on line 61`

`csstidy_print has a deprecated constructor in /app/public/wp-content/plugins/wp-foft-loader/includes/csstidy/class.csstidy_print.php on line 39`

`csstidy_optimise has a deprecated constructor in /app/public/wp-content/plugins/wp-foft-loader/includes/csstidy/class.csstidy_optimise.php on line 39`

`Warning: Cannot modify header information - headers already sent by (output started at /path/to/plugin/includes/csstidy/class.csstidy_print.php:39) in /wp-includes/pluggable.php on line 1251`

`Warning: Cannot modify header information - headers already sent by (output started at /path/to/plugin/includes/csstidy/class.csstidy_print.php:39) in /wp-includes/pluggable.php on line 1254`

**Comment by Cerdic** [comment]
Hi! I think you're getting an extra old version as this was fixed 7 years ago :)
See https://github.com/Cerdic/CSSTidy/commit/61d1c20f58df5d82328dd65e7fadfa4709f33216

And indeed, the wp-foft-loader plugin is embedding a v1.3 (whereas the current version is v1.6.5)

So you should make a request for update to the WP plugin authors

**Comment by seezee** [comment]
Thanks! I downloaded it from http://csstidy.sourceforge.net/. Wonder why they haven't kept it updated?

**Comment by Cerdic** [comment]
The original project seems quite dead and I never had any answer when pointing this updated version :/
