### ISSUE TITLE
Question about minimal optimization

### ISSUE THREAD

**Issue by gtbu** [Cerdic/CSSTidy#60]
I use cssmin which does too much with certain bootstrap.css'es  (and evtl. also others - sometimes strange problems with some css'es)

How can i adjust csstidy , so that it just removes / *.... * / and //... and unecessary spaces and otherwise changes as little as possible - regarding code optimization  ? The code may be a little bigger - i use mod_deflate anyway.

**Comment by Cerdic** [comment]
CSStidy proposes 4 differents optimization templates and somes specific settings for tuning.

I it is used as part of an open source CMS, and consequently in production on a lot of websites, including with Bootstrap (this is my favorite use case) without any trouble using the template `high` and default config except for `optimise_shorthands` that I set to `1`

So I think you can use it safely with BootStrap on your project with this settings if you want.
