### ISSUE TITLE
V2.1 .exe

### ISSUE THREAD

**Issue by chladnefazole** [Cerdic/CSSTidy#85]
Hello, I love this tool, but don't know how to build for Windows. Is there any way you could upload v2.1.0 (or latest version)?

I found older version on SourceForge: https://sourceforge.net/projects/csstidy/
But it is not supporting CSS3 well.

**Comment by Cerdic** [comment]
there is no executable binary for none of OS, I think it had been discontinued long time ago by the original author.
But there is a standalone php cli you can run with the command `php bin/pcsstidy`

https://github.com/Cerdic/CSSTidy/blob/master/bin/pcsstidy
