### ISSUE TITLE
simpletest deprecation

### ISSUE THREAD

**Issue by JamesRezo** [Cerdic/CSSTidy#87]
On [github](https://github.com/simpletest/simpletest), this tool has no release since 2019, thus it must be required with `dev-main` when using it as aa dev dependency with composer.

The webiste, https://simpletest.org/, seems down, and https://simpletest.sourceforge.net/ is not really up-to-date :)

Can we consider replacing it with phpunit?

**Comment by Cerdic** [comment]
that would be nice, and I also had this idea. But not the time to do it, so feel welcome if you want to do it :)
